project: 
  type: website
  output-dir: docs

website:
  title: "Spatial Data Science Lab<br>Dept. of Geography Education <br>Seoul National University"
  favicon: image/GIS-LAB_logo.png
  navbar:
    logo: image/SNU_logo_grey.png
    background: "#232E52"
    right:
      - href: index.qmd
        text: Home
      - href: professor/index.qmd
        text: Professor
      - text: Students
        menu:
          - href: students/MA_Students.qmd
            text: M.A. Students
          - text: PhD. Students
      - href: alumni/index.qmd
        text: Alumni
      - href: notice/list.html
        text: Notice
      - href: news.qmd
        text: News & Events
      - icon: github
        href: https://github.com/Sechang-Kim/gis-lab
  page-footer: 
    background: "#f0eeeb"
    left: |
      __Address:__ <br>
      10-203, College of Education, 1 Gwanak-ro, Gwanak-gu, Seoul 08826, Republic of Korea <br>
      __Tel__: 02-880-2557 | __Office Hour__: Mon-Fri, 09:00 - 18:00 | __Lab Manager__: [Woohyeong Kim](mailto:whk3423@snu.ac.kr)
    center: |
      Made with 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) and
      [![](https://posit.cloud/images/site-home/posit-logo-black-TM.svg){fig-alt="Posit" width=52px}](https://posit.co/) <br>
      First Developed by [Sechang Kim](mailto:sechangkim97@gmail.com)
    right: |
      Copyright &copy; 2024 [Seoul National University](https://snu.ac.kr/)<br>
      
    
format:
  html:
    theme: [cosmo, style.scss]
    css: style.css
    style: style.scss
    toc: true
    code-block-bg: true