project: 
  type: website

website: 
  title: "GIS Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: professor/professor.qmd
        text: Professor

format:
  html:
    theme: cosmo
    toc: true