project: 
  type: website
output-dir: docs

website: 
  title: "GIS Lab"
navbar:
  left:
  - href: index.qmd
text: Home
- href: professor.qmd
text: Professor

format:
  html:
  theme: cosmo
css: style.css
toc: true