project: 
  type: website
  output-dir: docs

website: 
  title: "GIS Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: professor/professor.qmd
        text: Professor
  page-footer: 
    background: "#F6F5F3"
    center: © 2024 &middot; Made with 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)

format:
  html:
    theme: cosmo
    toc: true