project: 
  type: website
  output-dir: docs

website:
  title: "Seoul National University<br>Dept' of Geography Education<br>GIS Laboratory"
  favicon: image/GIS-LAB_logo.png
  navbar:
    logo: image/SNU_logo_grey.png
    background: "#232E52"
    right:
      - href: index.qmd
        text: Home
      - href: professor/index.qmd
        text: Professor
      - text: Students
        menu:
          - text: "M.A. Students"
          - text: "PhD. Students"
      - href: alumni/index.qmd
        text: Alumni
      - href: news.qmd
        text: News & Events
      - icon: github
        href: https://github.com/Sechang-Kim/gis-lab
  page-footer: 
    background: "#232E52"
    center: © 2024 &middot; Made with 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)

format:
  html:
    theme: [cosmo, style.scss]
    css: style.css
    style: style.scss
    toc: true